spring:
  profiles:
    active: postgresql
  application:
    name: users-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

server:
  port: 9091
  servlet:
    context-path: /api/

logging:
  level:
    org.springframework.web: info
    dev.earlspilner.books: info