INSERT INTO loans (user_id, book_id, issued_at, due_to, returned_at)
VALUES (1, 101, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '14' DAY, NULL),
       (2, 102, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '7' DAY, NULL),
       (3, 103, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '30' DAY, NULL);
